kind: pipeline
type: docker
name: default

steps:
- name: build
  image: maven:3.6.3-openjdk-11
  commands:
  - mvn clean install -DskipTests
- name: docker  
  image: plugins/docker
  settings:
    username: prasadaws143  
    password: Volley@143
    repo: prasadaws143/drone-demo
